auth:
  adminUser: admin
  adminPassword: admin12345

service:
  type: NodePort

postgresql:
  enabled: true
  auth:
    postgresPassword: postgres12345
    password: keycloak12345
    database: keycloak
